service: serverless-rocketseat
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
  tracing:
    lambda: true

functions:
  deleteAccount:
    handler: src/app.deleteAccount
